name: mc-server-automation
runtime:
  name: python
  options:
    virtualenv: .venv
description: A minimal Azure Native Python Pulumi program
config:
  pulumi:tags:
    value:
      pulumi:template: ""
